Traceback (most recent call last):
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 57, in <module>
Traceback (most recent call last):
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 57, in <module>
    prep_era5_for_ilamb(variables[i])
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 29, in prep_era5_for_ilamb
    prep_era5_for_ilamb(variables[i])
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 29, in prep_era5_for_ilamb
    path = "/g/data/rt52/era5/single-levels/monthly-averaged/"+convert[var1]+"/*/*nc"
KeyError: 'huss'
    path = "/g/data/rt52/era5/single-levels/monthly-averaged/"+convert[var1]+"/*/*nc"
KeyError: 'hurs'
Traceback (most recent call last):
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 58, in <module>
    prep_era5_for_ilamb(variables[i+10])
  File "/home/548/eh6215/python/BARPA_evaluation/emma/ilamb/prep_era5.py", line 38, in prep_era5_for_ilamb
    g = iris.coord.AuxCoord(1/9.8,units='s/m2')
AttributeError: module 'iris' has no attribute 'coord'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36316,1],0]
  Exit code:    1
--------------------------------------------------------------------------
